In [5]:
# Import Packages
import re
import pandas as pd

def clean_barttovic_team(df: pd.DataFrame):
    df.columns = df.iloc[1]
    df = df.iloc[2:, 1:]
    return df
    
clean_barttovic_team(pd.read_csv("C:/Users/Peter/AppData/Local/GitHubDesktop/app-2.9.6/The_Perfect_Bracket/data/barttovic/Houston/barttovic_Houston_2008.csv")).head(100)

1,Category,Offense,Defense,Barthag,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Adj. Eff.,112.7,34,100.8,153,.7822,70,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,eFG%,49.8,172,49.1,130,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TO%,15.4,3,22.7,77,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,OR%,31.7,215,33.4,196,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,FTR,33.5,250,38.8,212,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,Postseason Tournament,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Tue 3-18\n3-18,A,NaN,108 (Ⅱ),NaN,Nevada,Nev,"W, 80-79",68,23-9,...,24-48,7-18,76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Mon 3-24\n3-24,H,NaN,124 (Ⅱ),NaN,Valparaiso,Valpo,"W, 91-67",70,24-9,...,17-33,7-25,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Wed 3-26\n3-26,A,NaN,72 (Ⅱ),NaN,Tulsa,Tulsa,"L, 73-69",64,24-10,...,16-38,8-22,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Date,NaN,Opponent,Result/Line,Record,WAB,Adj. O,Adj. D,PPP,eFG%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN