In [2]:
# Import Packages
import re
import pandas as pd

def clean_barttovic_team(df: pd.DataFrame):
    return df

1,Category,Offense,Defense,Barthag,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Adj. Eff.,112.7,34,100.8,153,.7822,70,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,eFG%,49.8,172,49.1,130,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TO%,15.4,3,22.7,77,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,OR%,31.7,215,33.4,196,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,FTR,33.5,250,38.8,212,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Adjust?\r\nSplit?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Shooting Stats,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3P%,36.1,117,33.8,97,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2P%,45.7,269,48.2,161,NaN,FT%,77.0,7,66.7,...,48.7,294,58.9,276,NaN,Adj. Tempo,71.0,42.0,NaN,•
11,FT%,77.0,7,66.7,55,NaN,Block %,10.8,289,10.6,...,71.0,42,NaN,•,NaN,NaN,NaN,NaN,NaN,NaN